// components/SalmonSpawner.vue
<template>
  <div class="salmon-spawner">
    <button @click="spawnSalmon" title="Spawn Salmon">
      <span class="plus">+</span><SvgoSalmonIcon class="salmon-button-icon" />
    </button>
  </div>
  <Salmon
    class="salmon"
    v-for="(salmon, index) in salmons"
    :key="index"
    :inverted="salmon.inverted"
    :startX="salmon.startX"
    :startY="salmon.startY"
  />
</template>

<script setup>
import { ref } from "vue";
import Salmon from "./Salmon.vue";

const salmons = ref([]);

const spawnSalmon = () => {
  // Get viewport dimensions
  const viewportWidth = window.innerWidth;
  const viewportHeight = window.innerHeight;

  // Salmon dimensions (approximate)
  const salmonWidth = 200;
  const salmonHeight = 200;

  // Generate random position within visible page bounds
  const startX = Math.random() * (viewportWidth - salmonWidth);
  const startY =
    Math.random() * (viewportHeight - salmonHeight) + window.scrollY;

  salmons.value.push({
    inverted: Math.random() > 0.5,
    startX,
    startY,
  });
};
</script>

<style scoped>
button {
  display: flex;
  justify-content: center;
  align-items: center;
  border: none;
  border-radius: 100px;
  height: 80px;
  width: 80px;
  font-size: 2rem;
  cursor: pointer;
  background-color: var(--water);
  box-shadow: inset 2px 0 0 4px var(--water);

  transition: box-shadow 0.1s ease;
}

button:hover {
  inset: 0;
  box-shadow: inset 2px 0 0 4px var(--darkWater);
}

button:active {
  background-color: var(--darkWater);
}

button .plus {
  color: white;
  font-family: var(--header-font-family);
  transition: transform 0.1s ease;
  position: absolute;
  left: 25%;
}

button:hover .plus {
  transform: scale(1.1);
}

button:active .plus {
  transform: scale(0.9);
}

.salmon-button-icon * {
  fill: revert-layer;
}
.salmon-button-icon {
  transform: scale(1.4);
  transition: transform 0.05s ease;
  position: absolute;
  right: 11%;
  top: 24%;
}

button:hover .salmon-button-icon {
  transform: scale(1.5);
}

button:active .salmon-button-icon {
  transform: scale(1.3);
}

.salmon-spawner {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  position: fixed;
  bottom: 0.5rem;
  right: 0.5rem;
  z-index: 4;
  perspective: 800px;
}

.salmon {
  position: absolute;
  z-index: 4;
  width: 200px;
  height: 200px;
  top: 0;
  left: 0;
  cursor: move;
}
</style>

// src/components/SalmonSpawner.tsx
import { useRef, useState } from "preact/hooks";

interface SalmonInstance {
  id: number;
  x: number;
  y: number;
  flipped: boolean;
}

const SALMON_SIZE = 200;

function Salmon({ salmon }: { salmon: SalmonInstance }) {
  const [pos, setPos] = useState({ x: salmon.x, y: salmon.y });
  const drag = useRef<{ startX: number; startY: number; baseX: number; baseY: number } | null>(null);

  const onPointerDown = (event: PointerEvent) => {
    event.preventDefault();
    (event.currentTarget as HTMLElement).setPointerCapture(event.pointerId);
    drag.current = {
      startX: event.clientX,
      startY: event.clientY,
      baseX: pos.x,
      baseY: pos.y,
    };
  };

  const onPointerMove = (event: PointerEvent) => {
    if (!drag.current) return;
    setPos({
      x: drag.current.baseX + (event.clientX - drag.current.startX),
      y: drag.current.baseY + (event.clientY - drag.current.startY),
    });
  };

  const onPointerUp = () => {
    drag.current = null;
  };

  return (
    <div
      style={{
        position: "absolute",
        left: 0,
        top: 0,
        transform: `translate(${pos.x}px, ${pos.y}px) ${salmon.flipped ? "scaleX(-1)" : ""}`,
        width: SALMON_SIZE,
        cursor: "move",
        touchAction: "none",
        zIndex: 50,
        pointerEvents: "auto",
      }}
      onPointerDown={onPointerDown}
      onPointerMove={onPointerMove}
      onPointerUp={onPointerUp}
    >
      <img
        src="/img/salmon-icon.svg"
        alt="Salmon"
        width={SALMON_SIZE}
        height={SALMON_SIZE}
        draggable={false}
        style={{ width: "100%", height: "auto" }}
      />
    </div>
  );
}

export default function SalmonSpawner() {
  const [salmons, setSalmons] = useState<SalmonInstance[]>([]);

  const spawnSalmon = () => {
    const x = Math.random() * Math.max(0, window.innerWidth - SALMON_SIZE);
    const y =
      Math.random() * Math.max(0, window.innerHeight - SALMON_SIZE) +
      window.scrollY;
    setSalmons((prev) => [
      ...prev,
      { id: Date.now() + prev.length, x, y, flipped: Math.random() > 0.5 },
    ]);
  };

  return (
    <>
      <div style={{ position: "absolute", top: 0, left: 0, overflow: "visible", pointerEvents: "none", width: "100%", height: 0 }}>
        {salmons.map((salmon) => (
          <Salmon key={salmon.id} salmon={salmon} />
        ))}
      </div>
      <button
        type="button"
        title="Spawn Salmon"
        onClick={spawnSalmon}
        class="fixed bottom-4 right-4 z-40 flex h-10 w-10 cursor-pointer items-center justify-center rounded-full border-none bg-water font-mono text-xl leading-none text-bg shadow-md transition-transform duration-100 hover:scale-110"
      >
        +
      </button>
    </>
  );
}
